// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartOnFhirDemo;

#nullable disable

namespace SmartOnFhirDemo.Migrations
{
    [DbContext(typeof(AccessLogContext))]
    [Migration("20260904002428_LaunchIdOnAccessLog")]
    partial class LaunchIdOnAccessLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("SmartOnFhirDemo.AccessLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FhirUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuerOrigin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LaunchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LaunchId", "Id");

                    b.HasIndex("IssuerOrigin", "PatientId", "OccurredAt");

                    b.ToTable("AccessLog", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
